DRYDOCK_INIT_JOBS: true
K8S_NAMESPACE: testing-openedx
PLUGINS:
- forum
- mfe
- drydock
DRYDOCK_BYPASS_CADDY: false
DRYDOCK_FLOWER: false
DRYDOCK_INGRESS: false
DRYDOCK_DEBUG: false
DRYDOCK_ENABLE_MULTITENANCY: false
DRYDOCK_ENABLE_SCORM: false
DRYDOCK_POD_LIFECYCLE: false
DRYDOCK_AUTO_TLS: false
DRYDOCK_NEWRELIC_LICENSE_KEY: ""
DRYDOCK_INGRESS_LMS_EXTRA_HOSTS: []
DRYDOCK_INGRESS_EXTRA_HOSTS: []
DRYDOCK_PDB_MINAVAILABLE_PERCENTAGE_MFE: 0
DRYDOCK_PDB_MINAVAILABLE_PERCENTAGE_FORUM: 0
DRYDOCK_PDB_MINAVAILABLE_PERCENTAGE_CADDY: 0
DRYDOCK_PDB_MINAVAILABLE_PERCENTAGE_LMS: 0
DRYDOCK_PDB_MINAVAILABLE_PERCENTAGE_LMS_WORKER: 0
DRYDOCK_PDB_MINAVAILABLE_PERCENTAGE_CMS: 0
DRYDOCK_PDB_MINAVAILABLE_PERCENTAGE_CMS_WORKER: 0
